/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pandarow_chinese_util_speex_Speex */

#ifndef _Included_com_pandarow_chinese_util_speex_Speex
#define _Included_com_pandarow_chinese_util_speex_Speex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    cancelNoiseInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_cancelNoiseInit
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    cancelNoisePreprocess
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_cancelNoisePreprocess
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    cancelNoiseDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_cancelNoiseDestroy
  (JNIEnv *, jobject);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    encode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_encode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_decode
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    en
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_en
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    de
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_de
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    encodeArray
 * Signature: ([SI[B)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_encodeArray
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray);

/*
 * Class:     com_pandarow_chinese_util_speex_Speex
 * Method:    decodeArray
 * Signature: ([BI[S)I
 */
JNIEXPORT jint JNICALL Java_com_pandarow_chinese_util_speex_Speex_decodeArray
  (JNIEnv *, jobject, jbyteArray, jint, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
